field: 8fcb881c-b94d-4ba7-bc40-1be1a96f7320 # About Accordion
fieldLayouts:
  9d26685c-deb5-436d-8aac-2ca0ccf87506:
    tabs:
      -
        elements:
          -
            fieldUid: c85e8fbb-3446-42c2-a104-323ac7f69b1d # Item Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0560f0d2-b031-47fd-9e82-8ce36f49cb14 # Item Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0560f0d2-b031-47fd-9e82-8ce36f49cb14: # Item Content
    columnSuffix: tyvnpbqp
    contentColumnType: text
    fieldGroup: null
    handle: itemContent
    instructions: ''
    name: 'Item Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c85e8fbb-3446-42c2-a104-323ac7f69b1d: # Item Header
    columnSuffix: zfdskgip
    contentColumnType: text
    fieldGroup: null
    handle: itemHeader
    instructions: ''
    name: 'Item Header'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: accordionItem
name: 'Accordion Item'
sortOrder: 1
