fieldLayouts:
  9cec6ffa-71a7-48a2-8ac5-7f421d3657ea:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98f02abd-a1bd-4a02-ad02-f9a090671bbf
            warning: null
            width: 100
          -
            fieldUid: c6045d05-9d13-43d9-995a-6235c9d06de7 # Number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94421db1-af24-421e-b7eb-ad2b9d766436
            warning: null
            width: 100
          -
            fieldUid: 4c9990d5-e7cf-4126-ae69-b11e34291f27 # Default Crop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddb36c42-aaf0-4ad7-8000-6f06cae30f3f
            warning: null
            width: 100
          -
            fieldUid: 27f1f900-5a51-4a28-a79a-a96fa74eb615 # Color Indicator
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c50424b-e86e-4b0c-baab-9af4972f8d42
            warning: null
            width: 100
          -
            fieldUid: bbffa576-6915-45bb-9e6e-d24d714421f8 # Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6a88807-cb6f-4eef-9774-efd7dd47a52c
            warning: null
            width: 100
        name: Content
        uid: 748ce54b-e674-4591-b409-8f47e2968930
handle: default
hasTitleField: false
name: Default
section: a0860ef3-3c9d-4ab4-a971-81d23723c2f3 # W3G Farms
sortOrder: 1
titleFormat: '{number}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
