fieldLayouts:
  9078dd43-89b9-4bb6-bef9-e1f7542447be:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e75883bb-69be-4651-9f57-a8a27c62ce54
            warning: null
            width: 100
          -
            fieldUid: 28743f9e-a466-47a2-83f1-6fd07759ae6c # Crop ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba22a737-1922-4cf7-ac17-bf90c4315d6b
            warning: null
            width: 100
          -
            fieldUid: 0287dd5d-2c33-42d6-8978-4862e482ccc4 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51fed9c7-bd49-4d53-b158-ae0d9691b3ae
            warning: null
            width: 100
          -
            heading: 'Sprout Time'
            type: craft\fieldlayoutelements\Heading
            uid: b81d6366-77e3-4bec-9652-fb7c7149398f
          -
            fieldUid: 85bf3862-4ad8-412f-8440-a686e5b9ca0b # Sprout Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcad1486-327d-4539-b859-fc3545cc2570
            warning: null
            width: 100
        name: Content
        uid: e0631990-c76d-4f5b-8a40-b0de6ac050a9
handle: default
hasTitleField: true
name: Default
section: 69818518-9a42-4d35-baaa-84a94214981c # Crops
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
