fieldLayouts:
  9384530b-3eed-4ee4-936d-d4715eb3a6f7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: icons
handle: icons
hasUrls: true
name: Icons
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@assetBaseUrl/images/icons/v2'
