fieldLayouts:
  9fd177bf-f8ba-40f4-aaec-350ae3da4e49:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 87bcb163-f46d-4ca6-8362-a57aadc69a5f
            warning: null
            width: 100
        name: Content
        uid: 505de2b6-5434-4c90-99c2-599ca66e2d63
fs: videoLibrary
handle: videoLibrary
name: 'Video Library'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
