columnSuffix: rgxocwpk
contentColumnType: text
fieldGroup: 53bb1464-b0cd-4052-809a-dab32005fc02 # Common
handle: appSubheader
instructions: ''
name: 'App subheader'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
