columnSuffix: null
contentColumnType: string
fieldGroup: cfe15f5d-1adf-433b-9762-020ffb8390a1 # Farm
handle: defaultCrop
instructions: null
name: 'Default Crop'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: true
  source: null
  sources:
    - 'section:69818518-9a42-4d35-baaa-84a94214981c' # Crops
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
