columnSuffix: rueizjqp
contentColumnType: smallint(2)
fieldGroup: cda801fc-47b5-488d-a1e1-066860ab8050 # Crops
handle: minutes
instructions: ''
name: Minutes
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 60
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
