columnSuffix: cxtjelzu
contentColumnType: integer(10)
fieldGroup: cda801fc-47b5-488d-a1e1-066860ab8050 # Crops
handle: sproutTimeSeconds
instructions: 'In seconds'
name: 'Sprout Time'
searchable: false
settings:
  decimals: 0
  defaultValue: 10
  max: null
  min: 10
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
