dateModified: 1651098526
email:
  fromEmail: jorgeduardo.1994@gmail.com
  fromName: 'Pixels Tools'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2a6dbe62-c3c1-440b-b595-39b8061bbbc0: Crops # Crops
    08f82119-a2df-4da8-990b-aca5231c953b: Default # Default
    18d52844-51e2-44f6-bb5f-885e7dbbc311: Minutes # Minutes
    53bb1464-b0cd-4052-809a-dab32005fc02: Common # Common
    72a12008-61d1-46be-9a97-f87cc94a5987: Hours # Hours
    0287dd5d-2c33-42d6-8978-4862e482ccc4: Image # Image
    28743f9e-a466-47a2-83f1-6fd07759ae6c: 'Crop ID' # Crop ID
    47900d8a-89a6-4d23-b94c-200c0d4e0728: 'Pixels Tools' # Pixels Tools
    518081ba-c716-4eb2-9baf-9e2b6a599bc3: Home # Home
    3028913d-00b8-41f2-9d89-8165d3acf1dd: Seconds # Seconds
    38316602-88ba-4e10-acad-7b5bf1bb29c8: 'Sprout Time' # Sprout Time
    69818518-9a42-4d35-baaa-84a94214981c: Crops # Crops
    a2010028-13f0-42f3-a3e9-fc949380d98d: 'Pixels Tools' # Pixels Tools
    c1ace2f2-2cda-4869-84e0-42e69977523b: Home # Home
    cda801fc-47b5-488d-a1e1-066860ab8050: Crops # Crops
plugins:
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
system:
  edition: solo
  live: true
  name: 'Pixels Tools'
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
