dateModified: 1652886612
email:
  fromEmail: jorgeduardo.1994@gmail.com
  fromName: 'Pixels Tools'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  crops:
    hasUrls: true
    name: Crops
    settings:
      path: '@assetBasePath/images/crops'
    type: craft\fs\Local
    url: '@assetBaseUrl/images/crops'
  globals:
    hasUrls: true
    name: Globals
    settings:
      path: '@assetBasePath/images/globals'
    type: craft\fs\Local
    url: '@assetBaseUrl/images/globals'
  icons:
    hasUrls: true
    name: Icons
    settings:
      path: '@assetBasePath/images/icons/v2'
    type: craft\fs\Local
    url: '@assetBaseUrl/images/icons/v2'
meta:
  __names__:
    0eaf6050-ecac-48e0-81d3-c4c0c6fe12a3: 'Public Schema' # Public Schema
    2a6dbe62-c3c1-440b-b595-39b8061bbbc0: Crops # Crops
    2fd6534b-22cc-4fdf-84c1-2f9545b75bd1: 'Video Library' # Video Library
    5b773b1c-3e44-4c0c-bed8-91c9940a7a61: App # App
    6d5619c6-6d9b-45f9-91e8-0df172a2b08e: Icons # Icons
    08f82119-a2df-4da8-990b-aca5231c953b: Default # Default
    8fcb881c-b94d-4ba7-bc40-1be1a96f7320: 'About Accordion' # About Accordion
    9da0f2bd-7458-4e1e-a715-b4beb701a03a: About # About
    18d52844-51e2-44f6-bb5f-885e7dbbc311: Minutes # Minutes
    53bb1464-b0cd-4052-809a-dab32005fc02: Common # Common
    61f1a4f7-2a73-4cb7-a7e4-74542135ccd6: w3g # w3g
    72a12008-61d1-46be-9a97-f87cc94a5987: Hours # Hours
    149b3668-c786-4ca3-8a89-6bab166caa5b: 'Accordion Item' # Accordion Item
    0287dd5d-2c33-42d6-8978-4862e482ccc4: Image # Image
    0560f0d2-b031-47fd-9e82-8ce36f49cb14: 'Item Content' # Item Content
    1299b608-7157-4fe9-9a42-6299c974a09c: 'Video Library' # Video Library
    28743f9e-a466-47a2-83f1-6fd07759ae6c: 'Crop ID' # Crop ID
    47900d8a-89a6-4d23-b94c-200c0d4e0728: 'Pixels Tools' # Pixels Tools
    73909da2-2188-47c2-b430-e2d10487305b: 'App subheader' # App subheader
    518081ba-c716-4eb2-9baf-9e2b6a599bc3: Home # Home
    3028913d-00b8-41f2-9d89-8165d3acf1dd: Seconds # Seconds
    38316602-88ba-4e10-acad-7b5bf1bb29c8: 'Sprout Time' # Sprout Time
    69818518-9a42-4d35-baaa-84a94214981c: Crops # Crops
    a2010028-13f0-42f3-a3e9-fc949380d98d: 'Pixels Tools' # Pixels Tools
    aaae132f-cfb2-4a2c-8206-e4c8d3e834bd: About # About
    bbcf1668-e766-4952-afde-576ee16361c7: App # App
    c1ace2f2-2cda-4869-84e0-42e69977523b: Home # Home
    c85e8fbb-3446-42c2-a104-323ac7f69b1d: 'Item Header' # Item Header
    cda801fc-47b5-488d-a1e1-066860ab8050: Crops # Crops
    d5e6adb6-7ab6-4b01-ac40-a18997c7f5c6: 'Icon Picker' # Icon Picker
    dfaf12d4-4815-4d4d-966f-f7cb5f07d67c: w3g # w3g
    e663f665-5b34-4ab0-8696-35cd7c137cb6: 'App Header' # App Header
    e741494a-9a5f-4b19-bb87-7992c9722c03: Globals # Globals
plugins:
  icon-picker:
    edition: standard
    enabled: true
    licenseKey: IS015025JULRKPUBEF411Q07
    schemaVersion: 1.0.1
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix-manifest:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: 'Pixels-farms is a simple tool that helps farmers keep track of the crops they are currently farming.'
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '0'
            -
              - template
              - '{{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
system:
  edition: solo
  live: true
  name: 'Pixels Tools'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
