defaultPlacement: end
enableVersioning: true
handle: w3g
name: 'W3G Landing'
propagationMethod: all
siteSettings:
  47900d8a-89a6-4d23-b94c-200c0d4e0728: # Pixels Tools
    enabledByDefault: true
    hasUrls: true
    template: _components/pages/w3g.html
    uriFormat: w3g
type: single
